version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pocwisper-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - SECRET_KEY=change-this-in-production-to-a-secure-random-key
      - DATABASE_URL=sqlite:///./pocwisper.db
      - WHISPER_MODEL=openai/whisper-base
      - OLLAMA_URL=http://10.0.2.2:11434
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/pocwisper.db:/app/pocwisper.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:${BACKEND_PORT:-8000}
    container_name: pocwisper-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
